import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-48 bg-white flex flex-row items-center justify-between pl-52 pr-52">
          <h3>Ethiopia</h3>
          <div className="flex flex-row items-center gap-10">
            <h2>Deals</h2>
            <h2>About</h2>
            <h2>Popular</h2>
            <h2>Contact</h2>


          </div>
          <h2>Support</h2>
        </div>
        {children}
      </body>
    </html>
  );
}
